version: '3.4'

services:
  unpdfer:
    image: unpdfer
    build:
      context: .
      dockerfile: ./Dockerfile
    environment:
      NODE_ENV: production
    ports:
      - 5000:5000
      - 3210:3210
      - 9229:9229
    volumes: 
      - "./:/usr/src/app"
